= TD 5
:stem: latexmath

[latexmath] 
++++ 
\def\x{\mathbf{x}}
\def\y{\mathbf{y}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\var}{\operatorname{var}}
\newcommand{\E}{\operatorname{\mathbb{E}}}
\newcommand{\cor}{\operatorname{cor}}
\newcommand{\Prob}{\mathbb{P}}
\def\hbO{\hat{\beta_1}}
\def\hbT{\hat{\beta_2}}
\def\mx{\overline{\x}}
\def\my{\overline{\y}}
\def\u{\mathbf{u}}
++++

== 1. Exposants
Soit \(A=\left[\begin{array}{cc}4 & -3 \\2 & -1\end{array}\right]\). Calculez \(A^8\).

== 2. Projection
Soit \(\u_1=\left[\begin{array}{l}2\\5\\-1\end{array}\right]\), \(\u_2=\left[\begin{array}{l}-2\\1\\1\end{array}\right]\) et \(\y=\left[\begin{array}{l}1\\2\\3\end{array}\right]\).

* Montrez que la base \(S=\{\u_1,\u_2\}\) est orthogonale.
* Quelle est la projection de \(\y\) sur l'espace \(V\) engendré par \(S\) ? Écrivez cette projection dans la base \(S\).
* Quelle est la projection de \(\y\) sur \(V^{\bot}\) ?

== 3. Distance minimale
Soit \(V\) un sous espace de \(\mathbb{R}^n\). On définit la distance de \(\y\in \mathbb{R}^n\) à \(V\) comme : 

[latexmath]
++++
d(\y, V)=\min_{\x\in V} d(\x, \y).
++++

Soit \(\u_1=\left[\begin{array}{l}5\\-2\\1\end{array}\right]\), \(\u_2=\left[\begin{array}{l}1\\2\\-1\end{array}\right]\) et \(\y=\left[\begin{array}{l}-1\\-5\\10\end{array}\right]\).

* Calculez la distance de \(y\) à \(V\) si \(V\) est engendré par \(\{4 u_1, 2 u_2, 3 y\}\) (NB : aucun calcul n’est nécessaire)
* Calculez la distance de \(y\) à \(V\) si \(V\) est engendré par \(\{u_1, u_2\}\)
* Calculez la distance de \(y\) à \(V\) si \(V\) est engendré par \(\{u_1, u_2\}\) pour le produit scalaire associé à la métrique \(M=\left[\begin{array}{rrr}1 & 0&0 \\0 & 2&0\\0&0&1\end{array}\right]\).

== 4. Diagonalisation
Diagonalisez, si possible, la matrice \(A\) suivante :

\[
A=\left[\begin{array}{rrr}1 & 3&3 \\-3 & -5&-3\\3&3&1\end{array}\right].
\]

Tentez pour commencer de deviner les valeurs propres en utilisant votre intuition.

== 5. Dimensions et diagonalisation
Soit \(A\) une matrice \(4 \times 4\) dont les valeurs propres sont \(5, 3, -2\). Si \(\text{dim}(E_3)=2\), peut on diagonaliser \(A\) ?

Rappel : l'espace propre associé à une valeur propre \(\lambda\) de A est \(E_\lambda=\{\x\mid A\x=\lambda\x\}\). À titre d’exemple, nous avons pour l’exercice 4 : \(\text{dim}(E_{-2})=2\).

== 6. Diagonalisation again
Déterminez si \(A=\left[\begin{array}{rrr}2 & 4&3 \\-4 & -6&-3\\3&3&1\end{array}\right]\) est diagonalisable, sachant que
\(
p_A(\lambda)=-(\lambda-1)(\lambda+2)^2.
\)

//== 7.
//Soit $A=\left[\begin{array}{rrr}5 & -8&1 \\0 & 0&7\\0&0&-2\end{array}\right]$. Est-elle diagonalisable ?

