= TD4
:stem: latexmath

[latexmath] 
++++ 
\def\x{\mathbf{x}}
\def\y{\mathbf{y}}
\newcommand{\cov}{\operatorname{cov}}
\newcommand{\var}{\operatorname{var}}
\newcommand{\E}{\operatorname{\mathbb{E}}}
\newcommand{\cor}{\operatorname{cor}}
\newcommand{\Prob}{\mathbb{P}}
\def\hbO{\hat{\beta_1}}
\def\hbT{\hat{\beta_2}}
\def\mx{\overline{\x}}
\def\my{\overline{\y}}
\def\u{\mathbf{u}}
++++

== Six dés
- Montrer que la variance de \(D\), un lancer d’un dé à six faces, vaut \(35/12\).
- Calculer la variance de \(X\), la somme de six dés.
- Donnez un intervalle \(I\) tel que \(P[X \in I] ≥ 95\%\).
- En admettant l’approximation \(X \sim \mathcal{N}(E[X], \sigma[X])\), donnez le plus petit intervalle \(I\) tel que \(P[X \in I] ≥ 95\%\).

== Régression
On considère le modèle de régression linéaire simple \(\y = \beta_1+ \beta_2\x+ \epsilon\). 
Soit un échantillon \((x_i,y_i)_{1 ≤ i \leq 100}\) de statistiques résumées 	 

[latexmath] 
++++ 
\sum_{i=1}^{100} x_i = 0 , \sum_{i=1}^{100} x_i^2 = 400, \sum_{i=1}^{100} x_iy_i = 100, \sum_{i=1}^{100} y_i = 100, \hat\sigma^2=1.
++++

Exprimer les intervalles de confiance à \(95\%\) pour \(\beta_1\) et \(\beta_2\) en vous servant de la https://en.wikipedia.org/wiki/Student%27s_t-distribution#Table_of_selected_values[table des quantiles] de la loi de Student.

.Quantiles de la loi de Student
[%header, format=csv]
|===
include::Student’s t distribution.csv[]
|===


